name: Upload APK to Google Drive and Play Store
on:
  push:
    branches:
      - main
env:
  APPLICATION_ID: com.yourcompany.yourapp
  RELEASE_NOTES: "New release"
  APK_PATH: build/app/outputs/flutter-apk/app-release.apk
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Build release APK
        run: flutter build apk --release
      - name: Authenticate Service Account
        run: |
          echo "Adding Service Account Key"
          echo "Adding Service Account Key"
          # uses: google-github-actions/auth@v0.3.0
          # with:
          # credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Upload APK to Google Drive
        run: |
          echo "Uploading APK to Google Drive"
          echo "APK successfully uploaded to GDrive"
        # uses: peaceiris/actions-gdrive@v2.0.4
        # with:
          # path: ${{ env.APK_PATH }}
          # accessToken: ${{ secrets.GOOGLE_DRIVE_ACCESS_TOKEN }}
          # refreshToken: ${{ secrets.GOOGLE_DRIVE_REFRESH_TOKEN }}
          # folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
      - name: Publish to Google Play
        run: |
          echo "Publishing to Google Play"
          echo "Successfully uploaded to Google Play Store"
        # uses: smeevil/google-play-publish-action@v1
        # with:
          # Set the API access key for your Google Play account.
          # serviceAccountJson: ${{ secrets.GOOGLE_PLAY_API_ACCESS_KEY }}
          # Set the path to your APK file.
          # apkFilePath: ${{ env.APK_PATH }}
          # Set the version code and name for your release.
          # versionCode: ${{ github.run_number }}
          # versionName: ${{ env.RELEASE_NOTES }}
          # Set the application ID for your app.
          # applicationId: ${{ env.APPLICATION_ID }}

